### ISSUE TITLE
Configure the trigger beyond mode/position

### ISSUE THREAD

**Issue by jpike88** [chesleybrown/uservoice-trigger-directive#10]
I want to be able to identify my users. This directive has no way to pass a configuration object to Uservoice, which begs the question why I would even use it in the first place. There's no point making something Angular-like, if it comes with less functionality.

**Comment by chesleybrown** [comment]
There certainly is a point as it solved my needs and many others. 

I do agree that adding this functionality would be a useful asset and if you'd like to contribute a PR I would gladly review it.
