### ISSUE TITLE
Need a way to configure subdomain and project id

### ISSUE THREAD

**Issue by kienpham2000** [chesleybrown/uservoice-trigger-directive#5]
Similar to this:
https://github.com/ngHelper/ngHelperUserVoice#configure-the-module

Instead of hard-code:
https://github.com/chesleybrown/uservoice-trigger-directive/blob/master/src/service.uservoice.js#L11

**Comment by chesleybrown** [comment]
Whoops! I'm working on fixing this now! :racehorse:
